---
abstract: 'Create bubble-babble fingerprints'
author:
  - 'Benjamin Trott. All rights reserved.'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Digest-BubbleBabble
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/btrott/Digest-BubbleBabble.git
version: 0.02
